language: python
sudo: required
services:
  - docker

before_install:
  - mkdir /tmp/{crispr,websmash}
  - mkdir -p /tmp/databases/pfam && cd /tmp/databases/pfam
  - curl ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam27.0/Pfam-A.hmm.gz > Pfam-A.hmm.gz
  - gunzip Pfam-A.hmm.gz && sudo apt-get install hmmer && hmmpress Pfam-A.hmm
  - mkdir -p /tmp/databases/clusterblast && cd /tmp/databases/clusterblast
  - wget https://bitbucket.org/antismash/antismash/downloads/clusterblast_dmnd07.tar.xz
  - tar -xJf clusterblast_dmnd07.tar.xz && rm clusterblast_dmnd07.tar.xz
  - cd ${TRAVIS_BUILD_DIR}

install:
  - docker build -t bilille .
  - docker run --name bilille
    --publish 80:80
    --volume .:/config:ro
    --volume /tmp/databases:/databases:ro
    --volume /tmp/crispr:/crispr_detect/upload:rw
    --volume /tmp/websmash:/websmash/upload:rw
    bilille

script:
  - docker exec -i -t bilille /bin/bash -c "cd /crispr_detect && python -m unittest discover tests"
  - docker exec -i -t bilille /bin/bash -c "cd /websmash && pip install -r test_requirements.txt && python -m unittest discover tests"
  - docker exec -i -t bilille /bin/bash -c "run_crispr_detect -h"
  - docker exec -i -t bilille /bin/bash -c "run_antismash -h"
  - curl -I localhost

after_script:
  - docker rm -f bilille