version: '2'
services:

  antismash-redis:
    restart: always
    image: redis

  antismash-run:
    restart: always
    volumes:     
      - "/root/mydisk/ifb/data/antismash/upload:/upload:rw"
      - "/root/mydisk/ifb/antismash/data/databases:/databases:ro"
    links:
      - antismash-redis:redis
    image: antismash/runsmash-lite
    environment:
      - ANTISMASH_EMAIL_FROM=loic.couderc@univ-lille1.fr
      - ANTISMASH_EMAIL_ERROR=loic.couderc@univ-lille1.fr
      - ANTISMASH_EMAIL_HOST=smtps.univ-lille1.fr
      - ANTISMASH_EMAIL_ENCRYPT=TLS
      - ANTISMASH_EMAIL_USER=lcouderc
      - ANTISMASH_EMAIL_PASSWORD=********
    command: /runsmash/runSMASH --queue redis://redis/0 --workdir /upload --statusdir /upload/status --name runner01 --long-running

  antismash-job-monitor:
    restart: always
    volumes:
      - "/root/mydisk/ifb/data/antismash/upload:/upload"
      - "/root/mydisk/ifb/data/antismash/websmash:/config"
    links:
      - antismash-redis:redis

    image: antismash/runsmash-lite
    command: /runsmash/watchStatus --queue redis://redis/0 --statusdir /upload/status


  nginx-proxy:  
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/etc/nginx/
    restart: always
    links:
      - site1
      - site2


  site1:
    restart: always
    volumes:
      - "/root/mydisk/ifb/data/antismash/upload:/upload"
      - "/root/mydisk/ifb/data/antismash/websmash:/config"
    links:
      - antismash-redis:redis
    image: antismash/websmash
#    container_name: site1


  site2:
    restart: always
    volumes:
      - /tmp/cripsr:/tmp
    build:
      context: ./crispr_detect
#    container_name: site2

#  site2:
#    restart: always
#    image: tutum/hello-world
#    container_name: site2





